/*
Copyright 2019, 2021, 2022, 2023 The Multi-Cluster App Dispatcher Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/project-codeflare/multi-cluster-app-dispatcher/pkg/apis/controller/v1beta1"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AppWrapperConditionApplyConfiguration represents an declarative configuration of the AppWrapperCondition type for use
// with apply.
type AppWrapperConditionApplyConfiguration struct {
	Type                    *v1beta1.AppWrapperConditionType `json:"type,omitempty"`
	Status                  *v1.ConditionStatus              `json:"status,omitempty"`
	LastUpdateMicroTime     *metav1.MicroTime                `json:"lastUpdateMicroTime,omitempty"`
	LastTransitionMicroTime *metav1.MicroTime                `json:"lastTransitionMicroTime,omitempty"`
	Reason                  *string                          `json:"reason,omitempty"`
	Message                 *string                          `json:"message,omitempty"`
}

// AppWrapperConditionApplyConfiguration constructs an declarative configuration of the AppWrapperCondition type for use with
// apply.
func AppWrapperCondition() *AppWrapperConditionApplyConfiguration {
	return &AppWrapperConditionApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *AppWrapperConditionApplyConfiguration) WithType(value v1beta1.AppWrapperConditionType) *AppWrapperConditionApplyConfiguration {
	b.Type = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *AppWrapperConditionApplyConfiguration) WithStatus(value v1.ConditionStatus) *AppWrapperConditionApplyConfiguration {
	b.Status = &value
	return b
}

// WithLastUpdateMicroTime sets the LastUpdateMicroTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastUpdateMicroTime field is set to the value of the last call.
func (b *AppWrapperConditionApplyConfiguration) WithLastUpdateMicroTime(value metav1.MicroTime) *AppWrapperConditionApplyConfiguration {
	b.LastUpdateMicroTime = &value
	return b
}

// WithLastTransitionMicroTime sets the LastTransitionMicroTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTransitionMicroTime field is set to the value of the last call.
func (b *AppWrapperConditionApplyConfiguration) WithLastTransitionMicroTime(value metav1.MicroTime) *AppWrapperConditionApplyConfiguration {
	b.LastTransitionMicroTime = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *AppWrapperConditionApplyConfiguration) WithReason(value string) *AppWrapperConditionApplyConfiguration {
	b.Reason = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *AppWrapperConditionApplyConfiguration) WithMessage(value string) *AppWrapperConditionApplyConfiguration {
	b.Message = &value
	return b
}
