/*
Copyright 2019, 2021, 2022, 2023 The Multi-Cluster App Dispatcher Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// CustomPodResourceTemplateApplyConfiguration represents an declarative configuration of the CustomPodResourceTemplate type for use
// with apply.
type CustomPodResourceTemplateApplyConfiguration struct {
	Replicas *int             `json:"replicas,omitempty"`
	Requests *v1.ResourceList `json:"requests,omitempty"`
	Limits   *v1.ResourceList `json:"limits,omitempty"`
}

// CustomPodResourceTemplateApplyConfiguration constructs an declarative configuration of the CustomPodResourceTemplate type for use with
// apply.
func CustomPodResourceTemplate() *CustomPodResourceTemplateApplyConfiguration {
	return &CustomPodResourceTemplateApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *CustomPodResourceTemplateApplyConfiguration) WithReplicas(value int) *CustomPodResourceTemplateApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithRequests sets the Requests field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Requests field is set to the value of the last call.
func (b *CustomPodResourceTemplateApplyConfiguration) WithRequests(value v1.ResourceList) *CustomPodResourceTemplateApplyConfiguration {
	b.Requests = &value
	return b
}

// WithLimits sets the Limits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Limits field is set to the value of the last call.
func (b *CustomPodResourceTemplateApplyConfiguration) WithLimits(value v1.ResourceList) *CustomPodResourceTemplateApplyConfiguration {
	b.Limits = &value
	return b
}
