/*
Copyright 2019, 2021, 2022, 2023 The Multi-Cluster App Dispatcher Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// DispatchDurationSpecApplyConfiguration represents an declarative configuration of the DispatchDurationSpec type for use
// with apply.
type DispatchDurationSpecApplyConfiguration struct {
	Expected *int  `json:"expected,omitempty"`
	Limit    *int  `json:"limit,omitempty"`
	Overrun  *bool `json:"overrun,omitempty"`
}

// DispatchDurationSpecApplyConfiguration constructs an declarative configuration of the DispatchDurationSpec type for use with
// apply.
func DispatchDurationSpec() *DispatchDurationSpecApplyConfiguration {
	return &DispatchDurationSpecApplyConfiguration{}
}

// WithExpected sets the Expected field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Expected field is set to the value of the last call.
func (b *DispatchDurationSpecApplyConfiguration) WithExpected(value int) *DispatchDurationSpecApplyConfiguration {
	b.Expected = &value
	return b
}

// WithLimit sets the Limit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Limit field is set to the value of the last call.
func (b *DispatchDurationSpecApplyConfiguration) WithLimit(value int) *DispatchDurationSpecApplyConfiguration {
	b.Limit = &value
	return b
}

// WithOverrun sets the Overrun field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Overrun field is set to the value of the last call.
func (b *DispatchDurationSpecApplyConfiguration) WithOverrun(value bool) *DispatchDurationSpecApplyConfiguration {
	b.Overrun = &value
	return b
}
