/*
Copyright 2019, 2021, 2022, 2023 The Multi-Cluster App Dispatcher Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// RequeuingTemplateApplyConfiguration represents an declarative configuration of the RequeuingTemplate type for use
// with apply.
type RequeuingTemplateApplyConfiguration struct {
	InitialTimeInSeconds *int    `json:"initialTimeInSeconds,omitempty"`
	TimeInSeconds        *int    `json:"timeInSeconds,omitempty"`
	MaxTimeInSeconds     *int    `json:"maxTimeInSeconds,omitempty"`
	GrowthType           *string `json:"growthType,omitempty"`
	NumRequeuings        *int    `json:"numRequeuings,omitempty"`
	MaxNumRequeuings     *int    `json:"maxNumRequeuings,omitempty"`
}

// RequeuingTemplateApplyConfiguration constructs an declarative configuration of the RequeuingTemplate type for use with
// apply.
func RequeuingTemplate() *RequeuingTemplateApplyConfiguration {
	return &RequeuingTemplateApplyConfiguration{}
}

// WithInitialTimeInSeconds sets the InitialTimeInSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitialTimeInSeconds field is set to the value of the last call.
func (b *RequeuingTemplateApplyConfiguration) WithInitialTimeInSeconds(value int) *RequeuingTemplateApplyConfiguration {
	b.InitialTimeInSeconds = &value
	return b
}

// WithTimeInSeconds sets the TimeInSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeInSeconds field is set to the value of the last call.
func (b *RequeuingTemplateApplyConfiguration) WithTimeInSeconds(value int) *RequeuingTemplateApplyConfiguration {
	b.TimeInSeconds = &value
	return b
}

// WithMaxTimeInSeconds sets the MaxTimeInSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxTimeInSeconds field is set to the value of the last call.
func (b *RequeuingTemplateApplyConfiguration) WithMaxTimeInSeconds(value int) *RequeuingTemplateApplyConfiguration {
	b.MaxTimeInSeconds = &value
	return b
}

// WithGrowthType sets the GrowthType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GrowthType field is set to the value of the last call.
func (b *RequeuingTemplateApplyConfiguration) WithGrowthType(value string) *RequeuingTemplateApplyConfiguration {
	b.GrowthType = &value
	return b
}

// WithNumRequeuings sets the NumRequeuings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NumRequeuings field is set to the value of the last call.
func (b *RequeuingTemplateApplyConfiguration) WithNumRequeuings(value int) *RequeuingTemplateApplyConfiguration {
	b.NumRequeuings = &value
	return b
}

// WithMaxNumRequeuings sets the MaxNumRequeuings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxNumRequeuings field is set to the value of the last call.
func (b *RequeuingTemplateApplyConfiguration) WithMaxNumRequeuings(value int) *RequeuingTemplateApplyConfiguration {
	b.MaxNumRequeuings = &value
	return b
}
