FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

ADD mcad-controller /usr/local/bin

RUN true \
    && microdnf update \
    && microdnf --nodocs install \
        curl \
    && microdnf clean all \
    && true

RUN cd /usr/local/bin && curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl

WORKDIR /usr/local/bin
