From ubuntu:18.04

ADD kar-controllers /usr/local/bin
ADD agent101config /root
ADD agent110config /root

ENTRYPOINT ["/usr/local/bin/kar-controllers"]

CMD ["--dispatcher","--agentconfigs","/root/agent110config:winsome-llama-kube-arbitrator,/root/agent101config:lanky-parrot-kube-arbitrator", "--v", "4", "--logtostderr"]

RUN apt-get update
RUN apt-get -y upgrade
