apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: nginx
      resources:
        requests:
          cpu: 1045m
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
