apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instascale-cr
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
  - get
  - create
  - update
  - delete
  - patch

- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - machine.openshift.io
  resources:
  - "*"
  verbs:
  - list
  - watch
  - get
  - create
  - update
  - delete
  - patch

- apiGroups:
  - mcad.ibm.com
  resources:
  - appwrappers
  verbs:
  - list
  - watch
  - get
  - create
  - update 
  - delete
  - patch
