/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	quotasubtreev1 "github.com/project-codeflare/multi-cluster-app-dispatcher/pkg/apis/quotaplugins/quotasubtree/v1"
)

// FakeQuotaSubtrees implements QuotaSubtreeInterface
type FakeQuotaSubtrees struct {
	Fake *FakeQuotasubtreeV1
	ns   string
}

var quotasubtreesResource = schema.GroupVersionResource{Group: "quotasubtree", Version: "v1", Resource: "quotasubtrees"}

var quotasubtreesKind = schema.GroupVersionKind{Group: "quotasubtree", Version: "v1", Kind: "QuotaSubtree"}

// Get takes name of the quotaSubtree, and returns the corresponding quotaSubtree object, and an error if there is any.
func (c *FakeQuotaSubtrees) Get(ctx context.Context, name string, options v1.GetOptions) (result *quotasubtreev1.QuotaSubtree, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(quotasubtreesResource, c.ns, name), &quotasubtreev1.QuotaSubtree{})

	if obj == nil {
		return nil, err
	}
	return obj.(*quotasubtreev1.QuotaSubtree), err
}

// List takes label and field selectors, and returns the list of QuotaSubtrees that match those selectors.
func (c *FakeQuotaSubtrees) List(ctx context.Context, opts v1.ListOptions) (result *quotasubtreev1.QuotaSubtreeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(quotasubtreesResource, quotasubtreesKind, c.ns, opts), &quotasubtreev1.QuotaSubtreeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &quotasubtreev1.QuotaSubtreeList{ListMeta: obj.(*quotasubtreev1.QuotaSubtreeList).ListMeta}
	for _, item := range obj.(*quotasubtreev1.QuotaSubtreeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested quotaSubtrees.
func (c *FakeQuotaSubtrees) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(quotasubtreesResource, c.ns, opts))

}

// Create takes the representation of a quotaSubtree and creates it.  Returns the server's representation of the quotaSubtree, and an error, if there is any.
func (c *FakeQuotaSubtrees) Create(ctx context.Context, quotaSubtree *quotasubtreev1.QuotaSubtree, opts v1.CreateOptions) (result *quotasubtreev1.QuotaSubtree, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(quotasubtreesResource, c.ns, quotaSubtree), &quotasubtreev1.QuotaSubtree{})

	if obj == nil {
		return nil, err
	}
	return obj.(*quotasubtreev1.QuotaSubtree), err
}

// Update takes the representation of a quotaSubtree and updates it. Returns the server's representation of the quotaSubtree, and an error, if there is any.
func (c *FakeQuotaSubtrees) Update(ctx context.Context, quotaSubtree *quotasubtreev1.QuotaSubtree, opts v1.UpdateOptions) (result *quotasubtreev1.QuotaSubtree, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(quotasubtreesResource, c.ns, quotaSubtree), &quotasubtreev1.QuotaSubtree{})

	if obj == nil {
		return nil, err
	}
	return obj.(*quotasubtreev1.QuotaSubtree), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeQuotaSubtrees) UpdateStatus(ctx context.Context, quotaSubtree *quotasubtreev1.QuotaSubtree, opts v1.UpdateOptions) (*quotasubtreev1.QuotaSubtree, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(quotasubtreesResource, "status", c.ns, quotaSubtree), &quotasubtreev1.QuotaSubtree{})

	if obj == nil {
		return nil, err
	}
	return obj.(*quotasubtreev1.QuotaSubtree), err
}

// Delete takes name of the quotaSubtree and deletes it. Returns an error if one occurs.
func (c *FakeQuotaSubtrees) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(quotasubtreesResource, c.ns, name), &quotasubtreev1.QuotaSubtree{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeQuotaSubtrees) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(quotasubtreesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &quotasubtreev1.QuotaSubtreeList{})
	return err
}

// Patch applies the patch and returns the patched quotaSubtree.
func (c *FakeQuotaSubtrees) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *quotasubtreev1.QuotaSubtree, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(quotasubtreesResource, c.ns, name, pt, data, subresources...), &quotasubtreev1.QuotaSubtree{})

	if obj == nil {
		return nil, err
	}
	return obj.(*quotasubtreev1.QuotaSubtree), err
}
